---
title: "Joining Gapminder Data"
author: "Hoi-Ying Mak"
output: github_document
---

# Get the original data

```{r, echo = TRUE}
library(tidyverse)
library(gapminder)

gapminder
```

# Import the HIV data

```{r}
#Import and print the HIV data using read_csv
(hiv <- read_csv("data/gapminder_hiv.csv"))
```

# What is the relationship between HIV prevalence and life expectancy?

```{r}
#Use left join instead of inner join because requiring HIV rate data to have match for all variables in gapminder will result in a loss of valable observations. Use geom_point and geom_smooth to show the cases and trend simultaneously. 
(hiv_life <- left_join(gapminder, hiv)) %>%
  ggplot(aes(hivRate, lifeExp)) +
  geom_point() +
  geom_smooth() +
  labs(title = "HIV Rate and Life Expectancy",
       x = "HIV Rate(%)",
       y = "Life Expectancy")

#The graph shows that countries have lower (<2.5%) HIV rate generally have higher life expectancy. However, the point graph shows there are a few outliners that have medium HIV rate(~5%) but extremely low life expentancy (below 40). 
```

# Which continents have the most countries with missing HIV data?

```{r}
#Use full join so that the cells with HIV data are preserved after the merge of data frames. Then, filter these missing HIV data. Then, use fct_infreq to reorder continents by number of cases missing data. 
(hiv_life_2 <- full_join(gapminder, hiv)) %>%
  filter(is.na(hiv_life_2$hivRate)) %>%
  ggplot(aes(fct_infreq(continent))) +
  geom_bar() +
  labs(title = "Missing HIV data by Continents",
       x = "Continents",
       y = "Cases of missing data")
#Africa has the highest number of missing HIV data (>400 cases). Oceania, the least populated among all continents, has the lowest cases of missing HIV data (<50 cases).
```


## Session info

```{r, echo = TRUE}
devtools::session_info()
```


